version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - cd lambdas/order_validation && npm install
      - cd ../updating_donut_inventory && npm install
      - cd ../calculate_order_wait_time && npm install

  build:
    commands:
      - echo "Zipping Lambda functions..."
      - cd lambdas/order_validation && zip -r order_validation.zip index.js node_modules package.json
      - cd ../updating_donut_inventory && zip -r updating_donut_inventory.zip index.js node_modules package.json
      - cd ../calculate_order_wait_time && zip -r calculate_order_wait_time.zip index.js node_modules package.json

  post_build:
    commands:
      - echo "Checking if ZIP files exist..."
      - ls -R lambdas/  

      - echo "Deploying Lambda functions..."
      - aws lambda update-function-code --function-name order_validation --zip-file fileb://lambdas/order_validation/order_validation.zip
      - aws lambda update-function-code --function-name updating_donut_inventory --zip-file fileb://lambdas/updating_donut_inventory/updating_donut_inventory.zip
      - aws lambda update-function-code --function-name calculate_order_wait_time --zip-file fileb://lambdas/calculate_order_wait_time/calculate_order_wait_time.zip
